<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ClashUp.Server.Gateway</RootNamespace>
    <AssemblyName>ClashUp.Gateway</AssemblyName>
    <UserSecretsId>clashup-gateway-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClashUp.Server.Common\ClashUp.Server.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
    <PackageReference Include="Docker.DotNet" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Google.Cloud.Monitoring.V3" />
  </ItemGroup>

</Project>
